
package enumeracoes;

/**
 *
 * @author Heverton
 */
public enum Analises_Requeridas {
    UMIDADE, MATERIA_SECA, MATERIA_MINERAL, EXTRATO_ETEREO, PROTEINA_BRUTA, FIBRA_EM_DERTERGENTE_ACIDO, 
    FIBRA_EM_DERTEGENTE_NEUTRO,PROTEINA_INSULUVEL_EM_DETERGENTE_NEUTRO, 
    PROTEINA_INSULUVEL_EM_DETERGENTE_ACIDO, CARBOIDRATOS_TOTAIS, CARBOIDRATOS_NAO_FIBROSOS,
    LIGNINA, CELULOSE, 	HEMICELULOSE, ENERGIA_DISGESTIVEL, NUTRIENTES_DIGESTIVOS_TOTAIS;
}
