
CREATE TABLE IF NOT EXISTS PROFESSOR (
  ID_PROFESSOR SERIAL,
  NOME_PROFESSOR VARCHAR(55) NULL,
  DEPARTAMENTO VARCHAR(100) NULL,
  TELEFONE VARCHAR(12) NULL,
  EMAIL_PROFESSOR VARCHAR(100) NULL,
  PRIMARY KEY(ID_PROFESSOR)
);

CREATE TABLE IF NOT EXISTS SOLICITANTE (
  ID_SOLICITANTE SERIAL,
  ID_PROFESSOR SERIAL,
  NOME_SOLICITANTE VARCHAR(55) NULL,
  TELEFONE VARCHAR(12) NULL,
  EMAIL_SOLICITANTE VARCHAR(100) NULL,
  PRIMARY KEY(ID_SOLICITANTE),
  FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSOR (ID_PROFESSOR)
);

CREATE TABLE IF NOT EXISTS RESPONSAVEL (
  ID_REPONSAVEL SERIAL,
  ID_AMOSTRA SERIAL,
  NOME_RESPONSAVEL VARCHAR(55) NULL,
  DATA_RECEBIMENTO DATE NULL,
  HORA TIME NULL,
  ASSINATURA VARCHAR(55),
  PRIMARY KEY(ID_REPONSAVEL),
  FOREIGN KEY (ID_AMOSTRA) REFERENCES AMOSTRA (ID_AMOSTRA)
);

CREATE TABLE IF NOT EXISTS AMOSTRA (
  ID_AMOSTRA SERIAL,
  ID_SOLICITANTE SERIAL,
  ID_REPONSAVEL SERIAL,
  IDENTIFICACAO_AMOSTRA VARCHAR(18),
  DESCRICAO VARCHAR(60) NULL,
  FRASCOS INTEGER NULL,
  OBSERVACOES VARCHAR(100),
  DATA_ENTRADA DATE NULL,
  TIPO_AMOSTRA VARCHAR(55) NULL,
  PRIMARY KEY(ID_AMOSTRA),
  FOREIGN KEY (ID_SOLICITANTE) REFERENCES SOLICITANTE (ID_SOLICITANTE),
  FOREIGN KEY (ID_REPONSAVEL SERIAL) REFERENCES RESPONSAVEL (ID_REPONSAVEL SERIAL)
);




